[package]
name = "pandora-api"
version = "0.5.0"
edition = "2018"
authors = ["Will Page <compenguy@gmail.com>"]
license = "MIT AND WTFPL"
repository = "https://github.com/compenguy/pandora-api.git"
description = "Low-level bindings to the (unofficial) Pandora web api."

[dependencies]
thiserror = "1.0"
url = "2.2"
async-std = "1.9"
surf = "2.2"
rust-crypto = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
pandora-api-derive = "0.1"
