[package]
name = "pandora-api"
version = "0.2.0"
authors = ["Will Page <compenguy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1"
reqwest = { version = "0.10", features = ["json", "blocking"] }
rust-crypto = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
pandora-api-derive = { path = "./pandora-api-derive" }
